### ISSUE TITLE
бля братан как это нахуй запустить

### ISSUE THREAD

**Issue by Shmuterz** [W1xon/BlumClicker#1]
я в ахуе ваще

**Comment by Shmuterz** [comment]
мож небольшой гайдик сделать?

**Comment by Shmuterz** [comment]
кароч всё ахуенно но сделай так чтобы можно было в фулл афк оставить а то приходится самому нажимать чтобы начать играть снова

**Comment by W1xon** [comment]
Щас что-нибудь придумаю насчёт того, чтобы полностью афк можно было его оставить
